# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oidc < Formula
  desc "A simple command line tool to interact with Open ID Connect providers."
  homepage "https://github.com/sk1m/oidc-cli"
  version "0.0.9"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/sk1m/oidc-cli/releases/download/v0.0.9/oidc-cli_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "c6e4d1d93acb5bb2455bdec5d6882b80ea164ad6fddf7ac43731de99d3151771"

      def install
        bin.install "oidc"
        bash_completion.install "completions/oidc.bash" => "oidc"
        zsh_completion.install "completions/oidc.zsh" => "_oidc"
        fish_completion.install "completions/oidc.fish"
      end
    end
    on_arm do
      url "https://github.com/sk1m/oidc-cli/releases/download/v0.0.9/oidc-cli_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "5b251a290499ab55fe76e87cf49066e2275d5c1738ecab4fd8021cc3613d3ba0"

      def install
        bin.install "oidc"
        bash_completion.install "completions/oidc.bash" => "oidc"
        zsh_completion.install "completions/oidc.zsh" => "_oidc"
        fish_completion.install "completions/oidc.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sk1m/oidc-cli/releases/download/v0.0.9/oidc-cli_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "3cda24ada4f51ff0d52fa8333dd9bebf1822408f0502cbcabf3c79aafbfaf232"

        def install
          bin.install "oidc"
          bash_completion.install "completions/oidc.bash" => "oidc"
          zsh_completion.install "completions/oidc.zsh" => "_oidc"
          fish_completion.install "completions/oidc.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sk1m/oidc-cli/releases/download/v0.0.9/oidc-cli_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "b54df853b731cf5c3b07c5dcb7f4035dede53c9b1e2ed5e20cba45fc52011151"

        def install
          bin.install "oidc"
          bash_completion.install "completions/oidc.bash" => "oidc"
          zsh_completion.install "completions/oidc.zsh" => "_oidc"
          fish_completion.install "completions/oidc.fish"
        end
      end
    end
  end
end
