# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Oidc < Formula
  desc "A simple command line tool to interact with Open ID Connect providers."
  homepage "https://github.com/sk1m/oidc-cli"
  version "0.0.10"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/sk1m/oidc-cli/releases/download/v0.0.10/oidc-cli_Darwin_x86_64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "2dbb9e103e3be038e0a1d66b47f014f9b746e4249a567715ee959f2087799937"

      def install
        bin.install "oidc"
        bash_completion.install "completions/oidc.bash" => "oidc"
        zsh_completion.install "completions/oidc.zsh" => "_oidc"
        fish_completion.install "completions/oidc.fish"
      end
    end
    on_arm do
      url "https://github.com/sk1m/oidc-cli/releases/download/v0.0.10/oidc-cli_Darwin_arm64.tar.gz",
        headers: [
          "Accept: application/octet-stream",
          "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
        ]
      sha256 "b4cf543db48b3178ca523f7e0ad143ed0a77497c0722e9f3ba360f5bbb50d60c"

      def install
        bin.install "oidc"
        bash_completion.install "completions/oidc.bash" => "oidc"
        zsh_completion.install "completions/oidc.zsh" => "_oidc"
        fish_completion.install "completions/oidc.fish"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sk1m/oidc-cli/releases/download/v0.0.10/oidc-cli_Linux_x86_64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "c1663865f09d24dda67d97fee15479d06a8f63cd44b4d5977f960b3bb2bf29f1"

        def install
          bin.install "oidc"
          bash_completion.install "completions/oidc.bash" => "oidc"
          zsh_completion.install "completions/oidc.zsh" => "_oidc"
          fish_completion.install "completions/oidc.fish"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sk1m/oidc-cli/releases/download/v0.0.10/oidc-cli_Linux_arm64.tar.gz",
          headers: [
            "Accept: application/octet-stream",
            "Authorization: bearer #{ENV["HOMEBREW_GITHUB_API_TOKEN"]}"
          ]
        sha256 "99b3a03a26d47f7b2bd9c18f8126db479ca687f8d2406bdc1829148fba4e25f2"

        def install
          bin.install "oidc"
          bash_completion.install "completions/oidc.bash" => "oidc"
          zsh_completion.install "completions/oidc.zsh" => "_oidc"
          fish_completion.install "completions/oidc.fish"
        end
      end
    end
  end
end
